//! Embedder §3.A LOAD-BEARING single-source invariant (reviewer4 CONFIRMED
//! acceptance cond. #1): agend-terminal's `Cargo.lock` must contain EXACTLY ONE
//! `agentic-git-core` package, resolved from the vendored submodule PATH.
//!
//! ## Why this exists
//! P1b swaps the daemon's binding signer to `agentic_git_core::integrity_core::
//! sign_binding` (binding.rs) while the agend-git verifier-shim still verifies
//! bare-hex tags via its `#[path]` `integrity_core` copy. The whole no-drift
//! argument (§3.A) rests on the daemon-linked core and every other consumer being
//! ONE resolved source. If a stray `agentic-git-core = "x"` (registry) ever
//! coexists with the path one, cargo resolves TWO distinct packages: the daemon
//! could link one version while another component links another → the structural
//! single-source guarantee silently collapses back into the signer/verifier HMAC
//! drift it prevents (a drift in a security check fails silently: too-loose →
//! fail-open, too-strict → false-deny). This test is the mechanical bedrock under
//! §3.A — no registry+path/git duplicate AND no transitive registry copy.
//!
//! ## What it checks
//! Parses the committed `Cargo.lock`, collects every `[[package]]` named
//! `agentic-git-core`, and asserts (a) exactly ONE such package and (b) it has NO
//! `source = "registry+.."` / `"git+.."` line — a path/local dep is source-less
//! in Cargo.lock, so ANY `source` line means a registry/git copy leaked in.
//!
//! ## How the regression-proof works
//! `checker_fires_on_stray_registry_duplicate` feeds the SAME
//! `agentic_core_sources` parser a hand-poisoned lockfile string (the real path
//! entry + a stray registry copy) and asserts the guard the green test relies on
//! (len==1 && source-less) would FAIL — same code path, no mock-only branch.

use std::path::Path;

/// The `source` of every `agentic-git-core` package block in a Cargo.lock, in
/// file order. A path/local dependency has NO `source` line (`None`); a registry
/// or git dependency carries `source = "registry+.."` / `"git+.."` (`Some(..)`).
fn agentic_core_sources(lock: &str) -> Vec<Option<String>> {
    // Cargo.lock is a sequence of `[[package]]` array-of-tables. Split on the
    // delimiter and inspect each block for our EXACT package name (an exact-line
    // match so `name = "agentic-git-core-foo"` or a `"agentic-git-core",`
    // dependency-list entry can never false-match).
    lock.split("[[package]]")
        .filter(|block| {
            block
                .lines()
                .any(|l| l.trim() == r#"name = "agentic-git-core""#)
        })
        .map(|block| {
            block.lines().find_map(|l| {
                l.trim()
                    .strip_prefix("source = \"")
                    .and_then(|r| r.strip_suffix('"'))
                    .map(str::to_owned)
            })
        })
        .collect()
}

#[test]
fn cargo_lock_has_exactly_one_agentic_git_core_from_path() {
    let lock_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.lock");
    let lock = std::fs::read_to_string(&lock_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", lock_path.display()));

    let sources = agentic_core_sources(&lock);

    assert_eq!(
        sources.len(),
        1,
        "§3.A: expected EXACTLY ONE agentic-git-core package in Cargo.lock, found \
         {} — a second copy (registry+path/git duplicate or a transitive registry \
         pull) collapses the single-source drift guarantee. Sources: {sources:?}",
        sources.len()
    );
    assert!(
        sources[0].is_none(),
        "§3.A: the sole agentic-git-core must be the vendored submodule PATH source \
         (a path dep is source-less in Cargo.lock); found a registry/git source \
         {:?} — the daemon signer must link the SAME source as the shim verifier",
        sources[0]
    );
}

/// Regression-proof (RED-first): the parser + guard MUST fire on a stray registry
/// duplicate. Feeds the SAME `agentic_core_sources` entry point a poisoned
/// lockfile (the real path entry + a stray registry copy) and asserts the green
/// test's guard (len==1 && source-less) would FAIL — no mock-only code path.
#[test]
fn checker_fires_on_stray_registry_duplicate() {
    const POISONED: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "agend-terminal"
version = "0.10.0"
dependencies = [
 "agentic-git-core",
]

[[package]]
name = "agentic-git-core"
version = "0.2.0"
dependencies = [
 "hmac",
]

[[package]]
name = "agentic-git-core"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
"#;

    let sources = agentic_core_sources(POISONED);

    // The parser SEES both copies (the path one + the stray registry one)...
    assert_eq!(
        sources.len(),
        2,
        "parser must detect BOTH agentic-git-core copies in a poisoned lockfile"
    );
    // ...and the EXACT guard the green test asserts (len==1 && all source-less)
    // FAILS on this input — proving the invariant would fire in a real regression.
    let single_source_ok = sources.len() == 1 && sources.iter().all(Option::is_none);
    assert!(
        !single_source_ok,
        "a stray registry duplicate MUST trip the single-source guard"
    );
    // and the stray copy is correctly recognized as a registry source.
    assert!(
        sources
            .iter()
            .any(|s| s.as_deref() == Some("registry+https://github.com/rust-lang/crates.io-index")),
        "the stray copy must be recognized as a registry source"
    );
    // the agend-terminal block's `"agentic-git-core",` dependency line must NOT be
    // mistaken for a package (exact-line name match) — else the count would be 3.
    assert!(
        !sources.is_empty() && sources.len() == 2,
        "a dependency-list entry must not be counted as a package block"
    );
}
